import type { CanvasElement } from "./types";

type DistributiveOmit<T, K extends keyof T> = T extends unknown
  ? Omit<T, K>
  : never;

export type StarterElement = DistributiveOmit<CanvasElement, "id" | "zIndex">;

export interface Starter {
  id: string;
  name: string;
  description: string;
  elements: StarterElement[];
}

const M = 40;
const W = 800;
const innerW = W - 2 * M;

export const STARTERS: Starter[] = [
  {
    id: "notice-1col",
    name: "안내문 1단",
    description: "간단한 제목·본문·CTA 구성",
    elements: [
      {
        type: "text",
        x: M,
        y: 80,
        width: innerW,
        height: 50,
        content: "안내문 제목을 입력하세요",
        fontSize: 36,
        fontWeight: 800,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.3,
        letterSpacing: -0.5,
      },
      {
        type: "text",
        x: M,
        y: 150,
        width: innerW,
        height: 30,
        content: "부제 또는 한 줄 요약",
        fontSize: 18,
        fontWeight: 500,
        color: "#475569",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        type: "divider",
        x: M,
        y: 200,
        width: innerW,
        height: 2,
        color: "#1e40af",
        thickness: 3,
      },
      {
        type: "text",
        x: M,
        y: 230,
        width: innerW,
        height: 200,
        content:
          "본문을 입력하세요. 행간을 넉넉히 두고 핵심 정보를 간결하게 적습니다.\n\n· 항목 1\n· 항목 2\n· 항목 3",
        fontSize: 16,
        fontWeight: 400,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.7,
        letterSpacing: 0,
      },
      {
        type: "rectangle",
        x: M + innerW / 2 - 100,
        y: 470,
        width: 200,
        height: 56,
        fillColor: "#1e40af",
        borderRadius: 28,
        borderColor: "#1e40af",
        borderWidth: 0,
      },
      {
        type: "text",
        x: M + innerW / 2 - 100,
        y: 487,
        width: 200,
        height: 24,
        content: "자세히 보기",
        fontSize: 16,
        fontWeight: 700,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
    ],
  },

  {
    id: "seminar",
    name: "세미나 프로그램",
    description: "행사명·일시·본문·프로그램 표·CTA 구성",
    elements: [
      {
        type: "text",
        x: M,
        y: 60,
        width: 200,
        height: 24,
        content: "SEMINAR",
        fontSize: 13,
        fontWeight: 700,
        color: "#f59e0b",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 4,
      },
      {
        type: "text",
        x: M,
        y: 95,
        width: innerW,
        height: 90,
        content: "행사명을 입력하세요",
        fontSize: 40,
        fontWeight: 800,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.2,
        letterSpacing: -1,
      },
      {
        type: "text",
        x: M,
        y: 200,
        width: innerW,
        height: 26,
        content: "2026년 0월 0일(목) 10:00 - 16:00",
        fontSize: 18,
        fontWeight: 600,
        color: "#1e40af",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        type: "text",
        x: M,
        y: 230,
        width: innerW,
        height: 24,
        content: "장소를 입력하세요",
        fontSize: 15,
        fontWeight: 400,
        color: "#475569",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        type: "text",
        x: M,
        y: 280,
        width: innerW,
        height: 80,
        content: "행사 소개 본문을 입력하세요. 목적·대상·기대 효과를 간결히 적어주세요.",
        fontSize: 15,
        fontWeight: 400,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.7,
        letterSpacing: 0,
      },
      {
        type: "text",
        x: M,
        y: 380,
        width: innerW,
        height: 24,
        content: "PROGRAM",
        fontSize: 14,
        fontWeight: 700,
        color: "#1e40af",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 2,
      },
      {
        type: "table",
        x: M,
        y: 414,
        width: innerW,
        height: 240,
        rows: 5,
        cols: 3,
        cells: [
          ["시간", "발표 주제", "발표자"],
          ["10:00 - 10:10", "개회 / 환영사", "주관 기관"],
          ["10:10 - 11:00", "Session 1", "발표자 (소속)"],
          ["11:00 - 12:00", "Session 2", "발표자 (소속)"],
          ["12:00 - 13:00", "점심 식사", ""],
        ],
        hasHeader: true,
        headerBg: "#1e40af",
        headerColor: "#ffffff",
        bodyBg: "#ffffff",
        bodyColor: "#0f172a",
        borderColor: "#cbd5e1",
        fontSize: 14,
      },
      {
        type: "rectangle",
        x: M + innerW / 2 - 80,
        y: 690,
        width: 160,
        height: 160,
        fillColor: "#f59e0b",
        borderRadius: 80,
        borderColor: "#f59e0b",
        borderWidth: 0,
      },
      {
        type: "text",
        x: M + innerW / 2 - 80,
        y: 757,
        width: 160,
        height: 28,
        content: "접수하기",
        fontSize: 20,
        fontWeight: 800,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
    ],
  },

  {
    id: "program",
    name: "지원 프로그램",
    description: "타이틀·정보 박스·안내사항·CTA 버튼 구성",
    elements: [
      {
        type: "text",
        x: M,
        y: 60,
        width: 200,
        height: 24,
        content: "'26년 1차",
        fontSize: 13,
        fontWeight: 700,
        color: "#f59e0b",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 3,
      },
      {
        type: "text",
        x: M,
        y: 95,
        width: innerW,
        height: 90,
        content: "지원 프로그램 제목",
        fontSize: 38,
        fontWeight: 800,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.2,
        letterSpacing: -1,
      },
      {
        type: "text",
        x: M,
        y: 200,
        width: innerW,
        height: 60,
        content: "한 줄 부제 / 프로그램 개요를 입력하세요.",
        fontSize: 17,
        fontWeight: 400,
        color: "#475569",
        textAlign: "left",
        lineHeight: 1.6,
        letterSpacing: 0,
      },
      {
        type: "table",
        x: M,
        y: 290,
        width: innerW,
        height: 200,
        rows: 4,
        cols: 2,
        cells: [
          ["모집 기간", "2026년 5월 ~ 6월 28일"],
          ["신청 자격", "참여 자격을 적어주세요"],
          ["지원 내용", "지원 내용을 적어주세요"],
          ["지원 금액", "지원 금액 / 비율을 적어주세요"],
        ],
        hasHeader: false,
        headerBg: "#1e40af",
        headerColor: "#ffffff",
        bodyBg: "#ffffff",
        bodyColor: "#0f172a",
        borderColor: "#e2e8f0",
        fontSize: 14,
      },
      {
        type: "rectangle",
        x: M,
        y: 520,
        width: innerW,
        height: 140,
        fillColor: "#f8fafc",
        borderRadius: 8,
        borderColor: "#cbd5e1",
        borderWidth: 1,
      },
      {
        type: "text",
        x: M + 16,
        y: 536,
        width: innerW - 32,
        height: 24,
        content: "Notice",
        fontSize: 14,
        fontWeight: 700,
        color: "#1e40af",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 2,
      },
      {
        type: "text",
        x: M + 16,
        y: 568,
        width: innerW - 32,
        height: 100,
        content:
          "· 신청서 작성 후 이메일로 제출\n· 마감일 이후 접수 불가\n· 결과는 개별 통보",
        fontSize: 14,
        fontWeight: 400,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.7,
        letterSpacing: 0,
      },
      {
        type: "rectangle",
        x: M,
        y: 690,
        width: 220,
        height: 48,
        fillColor: "#1e40af",
        borderRadius: 24,
        borderColor: "#1e40af",
        borderWidth: 0,
      },
      {
        type: "text",
        x: M,
        y: 703,
        width: 220,
        height: 24,
        content: "신청 양식 1",
        fontSize: 15,
        fontWeight: 700,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        type: "rectangle",
        x: M + 240,
        y: 690,
        width: 220,
        height: 48,
        fillColor: "#1e40af",
        borderRadius: 24,
        borderColor: "#1e40af",
        borderWidth: 0,
      },
      {
        type: "text",
        x: M + 240,
        y: 703,
        width: 220,
        height: 24,
        content: "신청 양식 2",
        fontSize: 15,
        fontWeight: 700,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
    ],
  },
];
